name: continous-integration

on:
    push:
        branches-ignore: [ga-ignore-*]
    pull_request:
        branches-ignore: [ga-ignore-*]

jobs:
    coding-style:
        name: Run Banana
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/epitech/coding-style-checker:latest
        
        steps:
            - name: Checkout GH repo
              uses: actions/checkout@v4

            - name: Run coding-style-checker
              run: check.sh $(pwd) $(pwd)

            - name: Report banana result
              run: |
                NB_ERROR=$(cat coding-style-reports.log | wc -l)
                if [ $NB_ERROR -gt 0 ]; then
                    ERROR=$(cat coding-style-reports.log)
                    echo "::error title=$NB_ERROR errors found::$ERROR"
                    exit 1
                fi
                exit 0